version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/django_docker
    ports:
      - "8080:8080"
    environment:
        - local_env=local
        - debug=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=newrootpassword
      - MYSQL_DATABASE=docker_market_db
      - MYSQL_USER=django_docker_user
      - MYSQL_PASSWORD=newpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
    mysql_data: